import { useEffect, useState, type FormEvent } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Mail } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/auth")({
  validateSearch: (search: Record<string, unknown>) => ({ next: typeof search.next === "string" && search.next.startsWith("/") ? search.next : "/news/editor" }),
  head: () => ({ meta: [{ title: "News Editor Sign In | i2OL" },{ name:"description",content:"Private sign-in for the i2OL News editor."},{property:"og:title",content:"News Editor Sign In | i2OL"},{property:"og:description",content:"Private sign-in for the i2OL News editor."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }),
  component: AuthPage,
});

function AuthPage(){const {next}=Route.useSearch();const navigate=useNavigate();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [signup,setSignup]=useState(false);const [message,setMessage]=useState("");useEffect(()=>{void supabase.auth.getUser().then(({data})=>{if(data.user)void navigate({to:next});});},[navigate,next]);const submit=async(e:FormEvent)=>{e.preventDefault();setMessage("");if(signup){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth?next=${encodeURIComponent(next)}`}});if(error){setMessage(error.message);return;}if(!data.session){setMessage("Check your email to confirm your account, then return here to sign in.");return;}}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setMessage(error.message);return;}}await navigate({to:next});};const google=async()=>{sessionStorage.setItem("i2ol-auth-next",next);const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:`${window.location.origin}/auth?next=${encodeURIComponent(next)}`});if(result.error)setMessage(result.error.message);};return <main className="auth-shell"><div className="auth-panel"><p className="eyebrow">Private publishing</p><h1>{signup?"Create editor account":"News editor sign in"}</h1><p>Only the approved editor account can create and publish i2OL News articles.</p><form onSubmit={e=>void submit(e)}><label>Email<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<Input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label>{message&&<p className="editor-message" role="status">{message}</p>}<Button type="submit" className="w-full"><Mail/> {signup?"Create account":"Sign in"}</Button></form><div className="auth-divider"><span>or</span></div><Button className="w-full" variant="outline" onClick={()=>void google()}>Continue with Google</Button><button className="auth-switch" type="button" onClick={()=>{setSignup(!signup);setMessage("");}}>{signup?"Already have an account? Sign in":"Need an account? Create one"}</button></div></main>}