import { useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, CalendarPlus, Check, CircleDot, ExternalLink, Globe2, Link as LinkIcon, RotateCcw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const JOIN = "https://join.i2ol.org";
const competitions = [
  { key: "IDSOL", title: "International Data Science Olympiad", detail: "300+ teams · Data & machine learning", href: "https://2026.idsol.org", className: "comp-id", field: "DSAI", definition: "Data Science & Artificial Intelligence", categories: [["INFRA", "Enterprise infrastructure"], ["PROD", "Consumer products"]] as const },
  { key: "IQCOL", title: "International Quantum Computing Olympiad", detail: "Quantum algorithms & information theory", href: "https://2026.iqcol.org", className: "comp-iq", field: "QCIT", definition: "Quantum Computing & Information Theory", categories: [["APP", "Application proposals"], ["EXP", "Exploratory proposals"]] as const },
  { key: "IBCOL", title: "International Blockchain Olympiad", detail: "Web3 & decentralized solutions", href: "https://2026.ibcol.org", className: "comp-ib", field: "BCTT", definition: "Blockchain & Trust Technologies", categories: [["ARC", "Solution architecture"], ["DEV", "Solution development"]] as const },
];

const Section = ({ eyebrow, title, children, dark = false }: { eyebrow?: string; title: string; children: React.ReactNode; dark?: boolean }) => <section className={dark ? "section-dark" : "section"}><div className="section-inner">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="section-title">{title}</h2>{children}</div></section>;
const Hero = ({ label, title, text, children }: { label: string; title: string; text: string; children?: React.ReactNode }) => <section className="page-hero"><div className="bridge-grid" aria-hidden="true"/><div className="relative mx-auto max-w-[1440px] px-5 py-16 md:py-24 lg:px-8"><p className="eyebrow">{label}</p><h1 className="page-title">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground md:text-xl">{text}</p>{children}</div></section>;
const Actions = ({ secondary = true }: { secondary?: boolean }) => <div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><a href={JOIN}>Submit your project now <ArrowUpRight /></a></Button>{secondary && <Button asChild size="lg" variant="outline"><a href="/compete">Explore competitions <ArrowRight /></a></Button>}</div>;
const Cards = () => <div className="competition-grid">{competitions.map((c) => <a href={c.href} target="_blank" rel="noreferrer" className={`competition-card ${c.className}`} key={c.key}><div className="network-lines"/><div className="relative flex h-full flex-col"><div className="flex justify-between text-xs font-bold uppercase"><span>{c.key} 2026</span></div><h3>{c.title}</h3><p>{c.detail}</p><span className="mt-auto inline-flex items-center gap-2 text-sm font-bold">Visit competition <ArrowUpRight className="size-4" /></span></div></a>)}</div>;
const CategoryChoices = ({ competition }: { competition: (typeof competitions)[number] }) => {
  const [selected, setSelected] = useState(competition.categories[0][0]);
  return <article className={`category-picker ${competition.className}`}><span className="field-code">{competition.field}</span><h3>{competition.definition}</h3><div className="category-options" role="group" aria-label={`${competition.key} category`}>{competition.categories.map(([code, description]) => <Button type="button" variant="outline" className={selected === code ? "is-selected" : ""} aria-pressed={selected === code} onClick={() => setSelected(code)} key={code}><span><strong>{code}</strong><small>{description}</small></span><Check className="category-check" aria-hidden="true"/></Button>)}</div></article>;
};
const Stat = ({ value, label }: { value: string; label: string }) => <div className="stat"><strong>{value}</strong><span>{label}</span></div>;
const InfoGrid = ({ items }: { items: { title: string; text: string }[] }) => <div className="info-grid">{items.map((x, i) => <article className="info-item" key={x.title}><span className="item-index">{String(i + 1).padStart(2, "0")}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div>;
const Criteria = ({ items }: { items: [string, number][] }) => <div className="criteria">{items.map(([name, value]) => <div key={name}><div className="flex justify-between gap-4"><strong>{name}</strong><strong>{value}%</strong></div><div className="meter"><span style={{ width: `${value}%` }}/></div></div>)}</div>;

function Home() { return <><section className="home-hero"><div className="bridge-grid"/><div className="relative mx-auto flex min-h-[680px] max-w-[1440px] flex-col justify-end px-5 pb-16 pt-28 lg:px-8"><div className="max-w-5xl"><p className="eyebrow">The international KB Olympiad · Ninth anniversary</p><h1>International Olympiad in <span>Emerging Technologies</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Practical problem-solving competitions themed around emerging technologies. Submission is open on a rolling basis.</p><Actions /></div></div></section><Section eyebrow="The umbrella" title="Three disciplines. One common mission."><div className="chain-diagram"><a href="https://kb.institute">KB Institute</a><ArrowRight/><strong>i2OL</strong><ArrowRight/><span>IDSOL · IQCOL · IBCOL</span><ArrowRight/><em>ETO, optional</em></div><Cards/></Section><Section eyebrow="The method" title="From technology to real-world impact" dark><div className="grid gap-px bg-background/15 md:grid-cols-3">{competitions.map(c => <div className="p-7 md:p-10" key={c.field}><div className={`field-code field-code-${c.key.toLowerCase()}`}>{c.field}</div><h3 className="mt-6 text-xl font-bold">{c.definition}</h3><p className="mt-3 text-sm leading-6 text-background/65">Build practical high- or low-level applications, backed by a whitepaper and entrepreneurial thinking.</p></div>)}</div></Section></>; }

const aboutItems = [{title:"Evidence before hype",text:"Whitepapers establish the technology, system design, methodology, and evidence behind every proposal."},{title:"Prototype with purpose",text:"Concepts move beyond theory toward responsible implementations and measurable real-world impact."},{title:"Global by design",text:"Students connect across disciplines, education levels, and borders under one shared standard."}];
function About() { const countries="Australia, Bangladesh, Belgium, Brazil, Cambodia, Canada, China, Denmark, Egypt, Estonia, France, Germany, Hong Kong, Hungary, India, Indonesia, Iran, Iraq, Ireland, Italy, Japan, Kazakhstan, Kyrgyzstan, Malaysia, Mongolia, Morocco, Nepal, Netherlands, New Zealand, North Macedonia, Pakistan, Philippines, Poland, Romania, Russia, Saudi Arabia, Serbia, Singapore, South Korea, Spain, Sri Lanka, Sweden, Switzerland, Taiwan, Thailand, Türkiye, Ukraine, United Kingdom, United States, and Vietnam."; return <><Hero label="About i2OL" title="Ideas that can cross the bridge." text="An international emerging-technologies initiative under KB Institute, inspired by the Seven Bridges of Königsberg problem."/><Section eyebrow="Our mission" title="Sustainable. Responsible. Evidence-based."><InfoGrid items={aboutItems}/><div className="stats-row"><Stat value="4,000+" label="competitors in our community"/><Stat value="50+" label="participating countries and regions"/><Stat value="9" label="years of competition"/></div></Section><Section eyebrow="Worldwide community" title="Built across borders" dark><p className="country-list">{countries}</p><Button asChild variant="signal" className="mt-8"><a href="https://kb.institute">About KB Institute <ArrowUpRight/></a></Button></Section></>; }

function Compete() { return <><Hero label="Compete" title="Choose your technological frontier." text="Annual, global, project-based competitions for secondary and post-secondary students. Teams may have any number of members."><Actions secondary={false}/></Hero><Section eyebrow="2026 competitions" title="One format, three technical lenses"><Cards/><div className="category-picker-grid">{competitions.map(c=><CategoryChoices competition={c} key={c.key}/>)}</div></Section><Section eyebrow="Eligibility" title="Two streams, teams of any size" dark><div className="grid gap-px bg-background/15 md:grid-cols-2"><div className="p-8"><p className="eyebrow">SS · ISCED 2–3</p><h3 className="text-3xl font-bold">Secondary Schoolers</h3><p className="mt-3 text-background/65">For students in secondary education.</p></div><div className="p-8"><p className="eyebrow">PS · ISCED 4–8</p><h3 className="text-3xl font-bold">Post-Secondary Students</h3><p className="mt-3 text-background/65">Short-cycle, bachelor’s, master’s, doctoral, or equivalent levels.</p></div></div><div className="supervisor-note"><strong>Adult supervision</strong><p>If no team member is over 18, the team must add a supervisor who is at least 18 years old.</p></div></Section></>; }

function Registration() { const steps=[{title:"Build your profile",text:"Create a personal account at join.i2ol.org and complete your personal particulars."},{title:"Pick a primary competition",text:"Select IDSOL, IQCOL, or IBCOL as your project’s primary competition."},{title:"Name your team",text:"Choose a name preserved in your season record. It is not your project title; it may reflect a company idea, place, institution, or inside joke."},{title:"Set location & invite",text:"Set your location, then invite team members and supervisors."},{title:"Choose stream & category",text:"Pick SS (ISCED 2–3) or PS (ISCED 4–8), then one of your competition’s two categories."},{title:"Options & payment",text:"Optionally add a secondary competition, express interest in ETO, then continue to the fee calculator."}]; return <><div className="tip"><Sparkles/> <span><strong>Funding tip:</strong> Ask your school or government, or see whether a technology company can sponsor your research, development, and registration.</span></div><Hero label="Registration" title="Build your team. Start your record." text="Registration and submission run through join.i2ol.org. Team size is unrestricted, and work can continue after your first submission."/><Section eyebrow="Registration steps" title="Six moves from profile to payment"><InfoGrid items={steps}/><div className="mt-10"><h3 className="text-xl font-bold">Streams & categories</h3><div className="mt-4 grid gap-3 md:grid-cols-3">{competitions.map(c=><div className="definition" key={c.key}><span>{c.key}</span><p>{c.categories}</p></div>)}</div></div></Section><Deadlines/><Section eyebrow="Registration fees" title="Open the calculator for your competition" dark><div className="grid gap-3 md:grid-cols-3">{competitions.slice().reverse().map(c=><Button asChild variant="light" size="lg" key={c.key}><a href={`${c.href}/registration.html`}>{c.key} fee calculator <ArrowUpRight/></a></Button>)}</div><p className="mt-4 text-sm text-background/60">Scroll to the bottom of the registration page to find the calculator.</p></Section><Section eyebrow="Fee waiver" title="Three routes for consideration"><InfoGrid items={[{title:"Proof of hardship",text:"Official documentation showing severe financial constraints or local economic difficulty."},{title:"Proof of quality work",text:"A sample project whitepaper or verifiable evidence of exceptional prior technical work."},{title:"Supporting school",text:"Ask your institution to become a recognized Supporting School—the fastest route, with complimentary registrations."}]}/><div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href="/support/school">Apply as Supporting School</a></Button><Button asChild variant="outline"><a href="mailto:info@i2ol.org?subject=Fee%20Waiver%20Request%20-%20i2OL%202026">Contact for waiver review</a></Button></div><Actions secondary={false}/></Section></>; }

function Deadlines(){return <Section eyebrow="Submission deadlines" title="Submit early. Improve continuously."><div className="deadline-list"><div><strong>30 AUG</strong><span>Whitepaper & prototype submission</span></div><div><strong>20 SEP</strong><span>ETO pitch deck & posterboard · late entry case-by-case</span></div><div><strong>15 NOV · 23:59 UTC</strong><span>Whitepaper & prototype resubmission</span></div></div><p className="mt-5 text-muted-foreground">Whitepapers are mandatory for all. A prototype is mandatory for IBCOL DEV and optional for IBCOL ARC, IDSOL INFRA/PROD, and IQCOL APP/EXP.</p></Section>}
function Submission(){return <><Hero label="Submission" title="Make the idea legible—and testable." text="Use each competition’s hub for current templates and file specifications. Submit now, receive qualifier feedback, and keep improving."/><Section eyebrow="Core deliverables" title="What every project needs"><InfoGrid items={[{title:"Whitepaper · mandatory",text:"Required for every IDSOL, IBCOL, and IQCOL project."},{title:"Prototype · track-specific",text:"Mandatory for IBCOL DEV; optional for IBCOL ARC, IDSOL INFRA/PROD, and IQCOL APP/EXP."},{title:"ETO materials · qualified teams",text:"Pitch deck and posterboard are Phase 2 deliverables only for teams choosing the optional ETO event."}]}/><Cards/></Section><Section eyebrow="ETO format" title="Pitch clearly in the room" dark><InfoGrid items={[{title:"Posterboard",text:"KBI conference format, A0 landscape, one concise visual page, submitted as a compressed PDF."},{title:"Pitch deck",text:"16:9 landscape, visual-first, lower text density, unlimited pages, focused on the core concept and business logic."}]}/><Button asChild variant="signal" className="mt-8"><a href={JOIN}>Submit now <ArrowUpRight/></a></Button></Section></>}

const qualifier:[string,number][]=[["Practicality",40],["Technicality",30],["Explainability",20],["Innovativity",10]];
const finals:[string,number][]=[["Design Thinking Competency",40],["First Principles Competency",30],["Presentability",20],["Originality",10]];
const etoCriteria:[string,number][]=[["Technical Rigour",30],["Innovation",25],["Real-World Impact",25],["Presentation",20]];
function Adjudication(){return <><Hero label="Adjudication" title="Three stages. Three distinct outcomes." text="Qualification, ETO expo judging, and international final evaluation are separate processes with their own criteria."/><Section eyebrow="Evaluation framework" title="Compare each stage"><Tabs defaultValue="qualifier"><TabsList className="tab-list"><TabsTrigger value="qualifier">01 Qualifier</TabsTrigger><TabsTrigger value="eto">02 ETO Expo</TabsTrigger><TabsTrigger value="final">03 Final</TabsTrigger></TabsList><TabsContent value="qualifier" className="tab-panel"><h3>Qualification adjudication</h3><p>All three competitions use one common competency threshold. Results are pass/fail with detailed feedback, normally within two weeks of submission. Projects may be assigned to adjudicators from their represented country where applicable.</p><Criteria items={qualifier}/><p>Qualification opens access to ETO and final evaluation. If a paper is not accepted initially, teams can refine and resubmit—making the process a learning experience.</p></TabsContent><TabsContent value="eto" className="tab-panel"><h3>ETO expo judging</h3><p>This industry-facing evaluation is exclusively for qualified projects and does not affect i2OL competition results.</p><Criteria items={etoCriteria}/><p>Awards: Gold · top teams; Silver · runner-up; Bronze · third place; People’s Choice · highest public vote.</p></TabsContent><TabsContent value="final" className="tab-panel"><h3>International final evaluation</h3><p>Qualified projects are reviewed by an international panel using criteria specific to IDSOL, IBCOL, and IQCOL categories.</p><Criteria items={finals}/><p>Outcomes include Awards of Merit and Distinction, category medals by stream, Venture Capitalist’s Choice, and Sponsor’s Choice.</p><div className="mt-6 flex flex-wrap gap-3">{competitions.map(c=><Button asChild variant="outline" key={c.key}><a href={c.href}>{c.key} detailed rubric <ExternalLink/></a></Button>)}</div></TabsContent></Tabs></Section><PhaseStrip/></>}
function PhaseStrip(){return <Section eyebrow="Project journey" title="Qualification → opportunity → recognition" dark><div className="phase-strip"><div><b>01</b><span>i2OL Qualifier<br/>Fully online</span></div><ArrowRight/><div><b>02</b><span>ETO side quest<br/>Qualified projects</span></div><ArrowRight/><div><b>03</b><span>Final evaluation<br/>Fully online</span></div></div></Section>}

const dates: Array<[string, "i2OL" | "ETO", string, string, string?]> = [
  ["30 AUG","i2OL","Whitepaper & prototype submission","Phase 1"],
  ["ROLLING","i2OL","Qualification · feedback about two weeks after submission","Phase 1"],
  ["ROLLING","ETO","Application verification","Phase 2"],
  ["20 SEP","ETO","Pitch deck & posterboard · late case-by-case","Phase 2"],
  ["08–09 OCT","ETO","Western Conference · Inholland University of Applied Sciences, Netherlands","Phase 2","https://luma.com/ulakda43"],
  ["09 OCT","ETO","Western Conference results release","Phase 2"],
  ["10–11 OCT","ETO","Eastern Conference · Canadian International School of Hong Kong","Phase 2","https://luma.com/ixuz80ix"],
  ["11 OCT","ETO","Eastern Conference results release","Phase 2"],
  ["15 NOV · 23:59 UTC","i2OL","Whitepaper & prototype resubmission","Phase 3"],
  ["NOV–DEC","i2OL","International final judging period","Phase 3","/compete/adjudication"],
  ["25 DEC","i2OL","International results release","Phase 3"],
];
function Timeline(){return <><Hero label="Key dates" title="Submission is on a rolling basis." text="Submit now, get qualifier feedback, and keep improving your project until the final resubmission deadline."><div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href={JOIN}>Submit now <ArrowUpRight/></a></Button><Button asChild variant="outline"><a href="https://calendar.google.com/calendar/u/0?cid=Y185NDkxOGNmMzQwNzhjYjMzMWJiY2UxOWU0ZTM4M2U2ZjM4MDI3ODA1ZjNmZTkxNGM3YjY2ODZmOTIzZjUwQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20"><CalendarPlus/> Add Google Calendar</a></Button></div></Hero><Section eyebrow="2026 season" title="One continuous project journey"><div className="timeline">{dates.map(([date,type,title,phase,href])=>{const content=<><time>{date}</time><div><span>{type} · {phase}</span><h3>{title}</h3></div>{href&&<ArrowUpRight className="timeline-link-icon" aria-hidden="true"/>}</>; return href?<a href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} key={date+title} className={`timeline-entry ${type === "ETO" ? "is-eto":"is-i2ol"}`}>{content}</a>:<article key={date+title} className={type === "ETO" ? "is-eto":"is-i2ol"}>{content}</article>})}</div><div className="legend"><span><i className="bg-primary"/>i2OL milestone</span><span><i className="bg-signal"/>ETO milestone</span></div></Section></>}

function TeamsGame(){const nodes=["KB","i2OL","IDEA","PROOF","IMPACT"]; const [built,setBuilt]=useState(1); const complete=built===nodes.length; return <><Hero label="Teams · 2026" title="The field is still forming." text="Team listings are hidden while the competition is in progress. In the meantime, build the chain from institution to impact."/><Section eyebrow="Build the chain" title={complete ? "Bridge complete." : "Connect the next node."}><div className="game"><div className="game-chain">{nodes.map((n,i)=><div key={n} className={i<built?"active":""}><button onClick={()=>i===built&&setBuilt(v=>v+1)} aria-label={`Connect ${n}`} disabled={i!==built}><CircleDot/><span>{n}</span></button>{i<nodes.length-1&&<i/>}</div>)}</div><p>{complete?"Institution → olympiad → idea → proof → impact. That is the i2OL journey.":"Select the next pulsing node to extend the bridge."}</p><Button variant="outline" onClick={()=>setBuilt(1)}><RotateCcw/> Reset</Button></div></Section></>}

function Accolades(){return <><Hero label="Accolades" title="Recognition for work that can move." text="Awards distinguish project quality, competitive achievement, and the choices of investors and sponsors."/><Section eyebrow="Project quality standings" title="Readiness matters"><div className="grid gap-4 md:grid-cols-2"><article className="award major"><span>01</span><h3>Award of Distinction</h3><p>For top-tier projects ready for real-world implementation.</p></article><article className="award"><span>02</span><h3>Award of Merit</h3><p>For promising projects with potential for real-world implementation.</p></article></div></Section><Section eyebrow="Per stream & category" title="i2OL medals" dark><div className="medals"><div>Au <span>Gold</span></div><div>Ag <span>Silver</span></div><div>Br <span>Bronze</span></div></div><p className="mt-8 text-background/65">Awarded separately across SS and PS streams for IDSOL INFRA/PROD, IBCOL ARC/DEV, and IQCOL APP/EXP.</p></Section><Section eyebrow="Additional recognition" title="Selected by the ecosystem"><InfoGrid items={[{title:"Venture Capitalist’s Choice",text:"Recognition from investors evaluating real-world commercial potential."},{title:"Sponsor’s Choice Award",text:"Recognition from an i2OL partner for an exceptional project aligned with its field."}]}/><Cards/></Section></>}
function Qualifier(){const countries="Australia, Bangladesh, Belgium, Brazil, Cambodia, Canada, China, Denmark, Egypt, Estonia, France, Germany, Hong Kong, Hungary, India, Indonesia, Iran, Iraq, Ireland, Italy, Japan, Kazakhstan, Kyrgyzstan, Malaysia, Mongolia, Morocco, Nepal, Netherlands, New Zealand, North Macedonia, Pakistan, Philippines, Poland, Romania, Russia, Saudi Arabia, Serbia, Singapore, South Korea, Spain, Sri Lanka, Sweden, Switzerland, Taiwan, Thailand, Türkiye, Ukraine, United Kingdom, United States, and Vietnam".split(", "); return <><Hero label="Qualifier" title="Compete locally, then represent internationally." text="Regional qualifiers are announced as local hosts are confirmed. If none is available in your country, you compete directly at international level."/><Section eyebrow="How it works" title="A common global threshold"><Criteria items={qualifier}/><p className="mt-7 max-w-3xl leading-7 text-muted-foreground">Results arrive on a rolling basis, normally two weeks after submission. Qualified teams receive a nomination code and can access ETO and the international final evaluation.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href={JOIN}>Apply directly</a></Button><Button asChild variant="outline"><a href="mailto:info@i2ol.org">Contact us</a></Button></div></Section><Section eyebrow="Global network" title="A worldwide route to the international stage" dark><div className="global-network"><div className="global-orbit" aria-hidden="true"><Globe2/><span>50+</span></div><div className="country-cloud">{countries.map((country, index)=><span style={{ "--country-index": index } as React.CSSProperties} key={country}>{country.replace(/,? and$/, "")}</span>)}</div></div></Section><Section eyebrow="Host a regional" title="Regional chapters announced soon" dark><p className="max-w-2xl text-background/65">Governmental or non-governmental organizations with competition experience may apply to host a regional qualifier.</p><Button asChild variant="signal" className="mt-6"><a href="mailto:info@i2ol.org?subject=Host%20an%20i2OL%20Regional">Host a regional <ArrowUpRight/></a></Button></Section></>}

function Eto(){return <><Hero label="Optional side event" title="Emerging Technologies Olympiad" text="An industry-facing pitching station for qualified projects, with opportunities to meet supporters and pursue funding."/><Section eyebrow="Two conferences" title="Choose your stage"><div className="grid gap-4 md:grid-cols-2"><article className="event"><span>WEST · 08–09 OCT</span><h3>Netherlands</h3><p>Thursday–Friday · Inholland University of Applied Sciences</p><Button asChild variant="outline"><a href="https://nl.kb.institute">Event details <ArrowUpRight/></a></Button></article><article className="event"><span>EAST · 10–11 OCT</span><h3>Hong Kong SAR</h3><p>Saturday–Sunday · Canadian International School of Hong Kong</p><Button asChild variant="outline"><a href="https://hk.kb.institute">Event details <ArrowUpRight/></a></Button></article></div></Section><Section eyebrow="Phase 2 submission · 20 September" title="Built for a live pitch" dark><InfoGrid items={[{title:"Posterboard",text:"KBI format, A0 landscape, one concise visual page, compressed PDF."},{title:"Pitch deck",text:"16:9 landscape, visual-first and lower-density, with unlimited pages focused on concept and business logic."}]}/></Section><Section eyebrow="Expo judging" title="Separate from i2OL results"><Criteria items={etoCriteria}/><p className="mt-8 text-muted-foreground">Awards: Gold for top teams · Silver for runner-up · Bronze for third place · People’s Choice for the highest public vote.</p></Section></>}

const connectCards=[{title:"Lessons learned",text:"Stories, interviews, and technical reflections from the three competition communities.",href:"/connect/lessons"},{title:"News",text:"Umbrella announcements, media mentions, and updates across the network.",href:"/news"},{title:"Committees",text:"Steering and advisory communities across i2OL, IDSOL, IBCOL, and IQCOL.",href:"/connect/committees"},{title:"Collab",text:"Person-to-person networks connecting builders, educators, and industry.",href:"/connect/collab"},{title:"Alumni",text:"A continuing community for prior i2OL attendees.",href:"/connect/alumni"},{title:"Adjudicators",text:"Apply to bring technical and entrepreneurial expertise to project review.",href:"/connect/judge"}];
function Connect(){return <><Hero label="Connect" title="A network built person to person." text="Continue learning, volunteer your expertise, meet collaborators, or return to the community as an alumnus."/><Section eyebrow="The community" title="Find your way in"><div className="link-grid">{connectCards.map(x=><a href={x.href} key={x.href}><LinkIcon/><h3>{x.title}</h3><p>{x.text}</p><ArrowRight/></a>)}</div></Section></>}
function Lessons(){return <><Hero label="Lessons learned" title="Methods, mistakes, breakthroughs." text="Explore stories and videos from the specialist competition communities."/><Section eyebrow="Competition archives" title="Go deeper"><Cards/></Section></>}
function News(){return <><Hero label="News" title="Signals from across the network." text="Competition announcements, external coverage, and updates from i2OL and the three specialist communities."/><Section eyebrow="2026 season" title="Follow each newsroom"><Cards/><p className="mt-8 text-muted-foreground">Past-winner features will appear here as the 2026 season progresses.</p></Section></>}
function Committees(){return <><Hero label="Committees" title="Help steer the standard." text="Steering and Advisory Committees support i2OL, IDSOL, IBCOL, and IQCOL."/><Section eyebrow="Declare your contribution" title="Three ways to serve"><InfoGrid items={[{title:"STEAM",text:"Science, Technology, Engineering, Art, and Mathematics."},{title:"SHAPE",text:"Social sciences, Humanities, and the Arts for People and the Economy."},{title:"Cross-disciplinary",text:"Bridge technical review, education, entrepreneurship, and public impact."}]}/><div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href="https://join.i2ol.org/committees">Apply to a committee</a></Button><Button asChild variant="outline"><a href="https://calendar.app.google/WvKPze4Gmasm5f8aA">STEAM enquiry</a></Button><Button asChild variant="outline"><a href="https://calendar.app.google/48HsDz62o7TsQdYs5">SHAPE enquiry</a></Button></div></Section></>}
function SimpleConnect({kind}:{kind:"collab"|"alumni"|"judge"}){const copy: Record<typeof kind, [string,string,string]>={collab:["Collab","Networks that start with a conversation.","This space is dedicated to person-to-person networks across the i2OL community."],alumni:["Alumni","Your i2OL journey continues.","Prior i2OL attendee? Join the alumni community and stay connected to the network."],judge:["Adjudicator","Bring judgment. Build capability.","Apply to assess emerging-technology projects. You must create a join.i2ol.org account before opening the application."]}; const c=copy[kind];return <><Hero label={c[0]} title={c[1]} text={c[2]}/><Section eyebrow="Get involved" title="Make the next connection"><Button asChild size="lg"><a href={kind==="judge"?"https://join.i2ol.org/judge":"mailto:info@i2ol.org"}>{kind==="judge"?"Apply as adjudicator":"Contact the community"}<ArrowUpRight/></a></Button></Section></>}
function Media(){return <><Hero label="Media" title="The i2OL press desk." text="For contacts, approved brand materials, social media, and coverage enquiries."/><Section eyebrow="Media resources" title="Tell the story accurately"><InfoGrid items={[{title:"Contacts",text:"Media and general enquiries: info@i2ol.org."},{title:"Brand packages",text:"Request current i2OL and competition identity assets for approved use."},{title:"Social media",text:"Follow and share updates from i2OL and the three competition communities."}]}/><Button asChild><a href="mailto:info@i2ol.org?subject=i2OL%20Media%20Enquiry">Contact media <ArrowUpRight/></a></Button></Section></>}
function Journal(){return <><Hero label="Journal" title="Coming soon." text="An open-access future for the ideas developed through i2OL."/><Section eyebrow="Why a journal" title="Preserve the work behind the pitch"><p className="prose-lead">i2OL requires technical whitepapers to explain underlying technology, system design, or methodology because our mission centers on sustainable, responsible, and evidence-based innovation. We aim to archive, publish, and launch these ideas as open-access journal articles.</p></Section></>}

const supportMap={support:{label:"Support",title:"Make ambitious work possible.",text:"Supporting the i2OL community comes in many shapes and forms."},school:{label:"Supporting school",title:"Give students a supported start.",text:"Supporting schools receive up to two complimentary team registrations."},organization:{label:"Supporting organization",title:"Put industry insight within reach.",text:"Provide technical resources, mentorship, and informed access to emerging talent."},contributing:{label:"Contributing organization",title:"Bring the qualifier closer.",text:"Host regional qualifiers, run community events, and support neighboring ETOs and i2OL communities."}};
function Support({kind}:{kind:keyof typeof supportMap}){const x=supportMap[kind]; if(kind==="support")return <><Hero label={x.label} title={x.title} text={x.text}/><Section eyebrow="Ways to contribute" title="Choose your role"><div className="link-grid">{[["Supporting school","Up to two complimentary team registrations.","/support/school"],["Supporting organization","Mentorship, resources, and industry insight.","/support/organization"],["Host a regional","For experienced governmental or non-governmental organizations.","/support/contributing"],["Donate","Direct support for a chosen program.","/donate"],["Sponsor","Fund the prize pool, operations, outreach, or exhibitions.","/sponsor"]].map(([a,b,c])=><a href={c} key={c}><Check/><h3>{a}</h3><p>{b}</p><ArrowRight/></a>)}</div></Section></>; const copy=kind==="school"?"In return, partner schools are encouraged to educate students on emerging technologies, participate in events, and maintain dialogue with our committee. This is the most efficient fee-waiver route.":kind==="organization"?"Supporting organizations may be sponsors or investors, offering technical resources and mentorship while gaining early access to top emerging talent.":"Applicants must be a governmental or non-governmental organization with competition experience. Email an organization profile and evidence of experience."; return <><Hero label={x.label} title={x.title} text={x.text}/><Section eyebrow="Partnership" title="A practical exchange"><p className="prose-lead">{copy}</p><div className="mt-8 flex gap-3"><Button asChild><a href={`mailto:info@i2ol.org?subject=${encodeURIComponent(x.label+" application")}`}>Apply by email <ArrowUpRight/></a></Button><Button asChild variant="outline"><a href="mailto:info@i2ol.org?subject=i2OL%20Infographic">Request infographic</a></Button></div></Section></>}
function Donate(){return <><Hero label="Donate" title="Direct your support." text="Choose the i2OL, IBCOL, IQCOL, IDSOL, or ETO program you want your donation to support."/><Section eyebrow="Payment form" title="Donation portal"><p className="prose-lead">The payment form is being prepared. Contact us to arrange a direct contribution in the meantime.</p><Button asChild className="mt-7"><a href="mailto:info@i2ol.org?subject=i2OL%20Donation">Arrange a donation <ArrowUpRight/></a></Button></Section></>}
function Sponsor(){return <><Hero label="Sponsorship" title="Back the next practical breakthrough." text="Support projects directly or strengthen the competition platform around them."/><Section eyebrow="Invest in projects" title="Help ideas move to market"><p className="prose-lead">Provide direct pre-seed or seed backing for emerging-technology concepts. At ETO pitching events, teams present their strategic vision and technical capability to potential supporters.</p></Section><Section eyebrow="Be a sponsor" title="Put resources where they matter" dark><p className="max-w-3xl text-lg leading-8 text-background/70">Contributions fund prize pools, event operations, education, outreach, pitching, and exhibitions. Sponsors engage directly with the community and receive season-long visibility across newsletters, social channels, web, and print.</p><Button asChild variant="signal" className="mt-8"><a href="https://calendar.app.google/bYFzoDehoPmfrbVG6">Schedule an online meeting <ArrowUpRight/></a></Button></Section></>}
function Privacy(){return <><Hero label="Legal" title="Privacy Policy Statement" text="Please read this statement to understand our policy and practices on the collection, use, transfer, storage, and processing of personal data."/><Section eyebrow="Kingsbridge Institute Limited" title="Your data and this website"><div className="legal-copy"><p>By accessing this Website, you are consenting to this PPS.</p><p>Kingsbridge Institute Limited, also known as Königsberger Bridges Institute (“KBI”, “we”, “us” or “our”) pledges to comply with the requirements of the Personal Data (Privacy) Ordinance. We will ensure compliance by our staff with the highest security and confidentiality standards.</p><p>We protect the privacy of users of our website. Personal data collected from you will only be used for the specific purposes mentioned at collection, directly related purposes, and/or those in the relevant Personal Information Collection Statement.</p><p>We retain personal data only as long as necessary to fulfil its collection purpose, erase it thereafter, and protect it from unauthorised access. We keep it confidential and disclose it only for its collected purpose, where required by law, or as specified in the relevant statement.</p><p>You may request access to and correction of personal data held by us. Submit requests in writing to the KBI Data Protection Officer at <a href="mailto:dpo@kb.institute">dpo@kb.institute</a>, marked “Personal Data Access/Correction Request”. A processing fee may apply.</p><p>We may keep a non-identifying activity log to measure traffic and improve our websites. It may include IP address, operating system, network and browser type, approximate location, and device identifiers.</p><p>We use cookies on https://i2ol.org to analyse traffic, personalise content, and support targeted advertising on third-party websites. Google Analytics, YouTube, Google, and other parties may set cookies under their own policies. Continuing to use this website indicates agreement; declining cookies may limit some functions.</p><p>This PPS may change, with revisions posted here. Continued use after posting indicates acceptance. If English and Chinese versions conflict, English prevails. Enquiries: <a href="mailto:dpo@kb.institute">dpo@kb.institute</a>.</p></div></Section></>}

export type PageKey = "home"|"about"|"compete"|"registration"|"submission"|"adjudication"|"timeline"|"teams"|"accolades"|"qualifier"|"eto"|"connect"|"lessons"|"news"|"committees"|"collab"|"alumni"|"judge"|"media"|"journal"|"support"|"school"|"organization"|"contributing"|"donate"|"sponsor"|"privacy";
export function SitePage({page}:{page:PageKey}){const view=useMemo(()=>({home:<Home/>,about:<About/>,compete:<Compete/>,registration:<Registration/>,submission:<Submission/>,adjudication:<Adjudication/>,timeline:<Timeline/>,teams:<TeamsGame/>,accolades:<Accolades/>,qualifier:<Qualifier/>,eto:<Eto/>,connect:<Connect/>,lessons:<Lessons/>,news:<News/>,committees:<Committees/>,collab:<SimpleConnect kind="collab"/>,alumni:<SimpleConnect kind="alumni"/>,judge:<SimpleConnect kind="judge"/>,media:<Media/>,journal:<Journal/>,support:<Support kind="support"/>,school:<Support kind="school"/>,organization:<Support kind="organization"/>,contributing:<Support kind="contributing"/>,donate:<Donate/>,sponsor:<Sponsor/>,privacy:<Privacy/>})[page],[page]); return <main>{view}</main>}